version: '3.8'

services:
  db:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: expressexec
      MONGO_INITDB_ROOT_PASSWORD: expressexec
      MONGO_INITDB_DATABASE: expressexec
    ports:
      - '27017:27017'

  app:
    environment:
      - NODE_ENV=development
      - JWT_SECRET_KEY=my-super-secret
      - JWT_ISS=issuer-one
      - JWT_EXP=3600
    depends_on:
      - 'db'
    build: .
    ports:
      - '1234:1234'
    volumes:
      - .:/code
