name: Test & Publish

on:
  release:
    branches: [master]
    types: [published]
  pull_request:
    branches: [master]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@master

      - name: Install dependencies + peer deps
        run: npm ci && npm i express @jsmrcaga/executor


      - name: Test
        run: npm test

  publish:
    needs: [test]
    if: ${{ github.event_name == 'release' }}

    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@master

      - name: Set version
        run: npm version ${{ github.event.release.tag_name }} --git-tag-version=false

      - name: Publish to NPM registry
        run: npm publish
